spring:

  datasource:

    url: jdbc:mysql://192.168.1.157:3306/chatbot?useSSL=false

    username: navarrete01
    
    password: root

  jpa:

    show-sql: true

    hibernate:

      ddl-auto: update
      
      naming: 
      
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    properties:

      hibernate:       
        
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  thymeleaf:
  
    cache: false
        

